PRESETS = {
    'campus-eef': {'country': 'france', 'label': 'Études en France — guide 26 × 32 mm', 'width_mm': 26, 'height_mm': 32, 'dpi': 300, 'max_kb': 49, 'background': '#f1f5f9', 'source': 'https://www.rwanda.campusfrance.org/system/files/medias/documents/2024-10/Guidelines%20application%20student.pdf', 'note': 'Guide Études en France : environ 26 × 32 mm à 300 DPI. Limite de 50 Ko appliquée avec une marge. Suivez en priorité votre espace Campus France local.'},
    'campus-cm': {'country': 'france', 'label': 'Campus France Cameroun — Études en France', 'width_mm': 40, 'height_mm': 40, 'dpi': 300, 'max_kb': 50, 'background': '#f1f5f9', 'source': 'https://www.cameroun.campusfrance.org/system/files/medias/documents/2023-11/Guide%20candidature.pdf', 'note': 'Photo 4 × 4, 50 Ko maximum selon le guide local. Vérifiez les consignes affichées dans votre dossier.'},
    'fr-visa': {'country': 'france', 'label': 'France — visa / photo identité', 'width_mm': 35, 'height_mm': 45, 'dpi': 300, 'head_min_mm': 32, 'head_max_mm': 36, 'background': '#f1f5f9', 'source': 'https://www.service-public.fr/particuliers/vosdroits/F10619', 'note': 'Fond uni clair, blanc interdit pour la photo identité française. Contrôle humain nécessaire.'},
    'ca-temporary': {'country': 'canada', 'label': 'Canada — visa temporaire / études', 'width_mm': 35, 'height_mm': 45, 'dpi': 300, 'head_min_mm': 31, 'head_max_mm': 36, 'background': '#ffffff', 'source': 'https://www.canada.ca/fr/immigration-refugies-citoyennete/services/demande/formulaires-demande-guides/demande-visa-resident-temporaire-specifications-photographie.html', 'note': 'Cadre minimum 35 × 45 mm. Fond blanc ou de couleur claire. Les exigences de téléversement dépendent du portail.'},
    'ca-pr': {'country': 'canada', 'label': 'Canada — résidence permanente (numérique)', 'width_mm': 50, 'height_mm': 70, 'width_px': 1000, 'height_px': 1400, 'dpi': 508, 'max_kb': 4000, 'background': '#ffffff', 'no_retouch': True, 'source': 'https://www.canada.ca/en/immigration-refugees-citizenship/services/permanent-residents/card/photos.html', 'note': 'JPEG entre 715 × 1000 et 2000 × 2800 px, 4 Mo maximum. Export 1000 × 1400 px. Photo professionnelle originale, sans retouche ; informations du photographe à joindre selon le portail.'},
    'ca-pr-paper': {'country': 'canada', 'label': 'Canada — résidence permanente (papier)', 'width_mm': 50, 'height_mm': 70, 'dpi': 300, 'head_min_mm': 31, 'head_max_mm': 36, 'background': '#ffffff', 'no_retouch': True, 'source': 'https://www.canada.ca/en/immigration-refugees-citizenship/services/permanent-residents/card/photos.html', 'note': 'Tirage 50 × 70 mm, tête 31–36 mm, réalisé par un photographe professionnel sans altération. Mentions au verso nécessaires. La planche ne remplace pas une photo professionnelle.'},
    'de-visa': {'country': 'germany', 'label': 'Allemagne — visa biométrique', 'width_mm': 35, 'height_mm': 45, 'dpi': 300, 'head_min_mm': 32, 'head_max_mm': 36, 'background': '#f1f5f9', 'no_retouch': True, 'source': 'https://jaunde.diplo.de/cm-de/service/checkliste-schengen-2444244', 'note': 'Ambassade d’Allemagne à Yaoundé : photo 35 × 45 mm, biométrique, sans retouche, fond uni clair. Pour les titres émis en Allemagne, une transmission numérique agréée peut être requise.'},
    'us-visa': {'country': 'usa', 'label': 'États-Unis — DS-160 / visa', 'width_mm': 50.8, 'height_mm': 50.8, 'width_px': 600, 'height_px': 600, 'dpi': 300, 'max_kb': 240, 'head_min_ratio': .5, 'head_max_ratio': .69, 'background': '#ffffff', 'no_retouch': True, 'source': 'https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/photos.html', 'note': 'JPEG carré 600 × 600 minimum, 240 Ko maximum. Ne pas altérer votre apparence ni remplacer numériquement le fond. Décision finale par le service consulaire.'},
}

for preset in PRESETS.values():
    preset['verified_on'] = '2026-10-03'

def dimensions(preset):
    return (preset.get('width_px', round(preset['width_mm'] / 25.4 * preset['dpi'])), preset.get('height_px', round(preset['height_mm'] / 25.4 * preset['dpi'])))
