import home from '../../../pages/home.html?raw';
import { $ ,escape } from '../../shared/ui';
import { presets } from '../../entities/preset';
import { navigation } from '../../widgets/header';
export function staticPage(kind:string,root:HTMLElement){
  const header=$('header',new DOMParser().parseFromString(home,'text/html'))!.outerHTML;
  const content:Record<string,string>={
    privacy:`<h1>Politique de confidentialité</h1><p>DocuVisa.AI conserve votre nom, votre email, les fichiers importés, les réglages utilisés et les exports dans votre espace personnel. Ces données servent à traiter vos fichiers et à vous permettre de les télécharger à nouveau.</p><h2>Conservation des fichiers</h2><p>L’interface ne propose pas de suppression des travaux. Cette conservation doit être accompagnée d’une politique de durée, de sauvegarde et d’un contact responsable avant ouverture publique. Aucun stockage illimité ou perpétuel ne peut être garanti sans cette infrastructure.</p><h2>Accès et traitements</h2><p>Les conversions sont réalisées sur le serveur avec LibreOffice et des bibliothèques Python. Le détourage utilise un modèle de segmentation local ; aucun service de génération de texte n’est nécessaire. Les cookies de session sont réservés à la connexion.</p><p>Les obligations relatives aux données personnelles et les modalités d’exercice des droits doivent être précisées par l’exploitant. Cette page est une version de développement.</p>`,
    legal:`<h1>Mentions légales</h1><p>DocuVisa.AI est un service gratuit de conversion documentaire et de préparation d’images. L’exploitant, son adresse et son contact doivent être renseignés avant la mise en production publique.</p><h2>Résultats et vérification</h2><p>Les dimensions et le poids des images sont appliqués selon le préréglage choisi. Vérifiez toujours les règles de votre portail et la qualité du résultat avant dépôt. DocuVisa.AI n’est affilié à aucun consulat ni à Campus France et ne garantit pas l’acceptation d’un dossier.</p><h2>Gratuité</h2><p>Aucun paiement, abonnement ou filigrane n’est appliqué aux exports. Les coûts d’hébergement restent à la charge de l’exploitant.</p>`,
    standards:`<h1>Formats et sources officielles</h1><p>Choisissez une démarche précise. Les consignes affichées dans votre dossier priment sur un préréglage. Le format exporté ne certifie pas la pose, l’expression, l’éclairage ou l’acceptation consulaire.</p>${Object.values(presets).map(p=>`<h2>${escape(p.label)}</h2><p>${p.width_mm} × ${p.height_mm} mm${p.max_kb?` · ${p.max_kb} Ko maximum`:''}. ${escape(p.note)} <a href="${p.source}" target="_blank" rel="noopener">Source officielle</a></p>`).join('')}`,
  };
  root.innerHTML=header+`<main class="page-copy">${content[kind]}<a href="/studio">Ouvrir le studio photo</a></main>`;navigation();
}
